spring.application.name=Eventify
server.servlet.context-path=/api

# Configuración de H2 para que guarde en un archivo (Persistencia Real)
spring.datasource.url=jdbc:h2:file:./data/eventifydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Esto evita que se borre todo al reiniciar, solo actualiza la estructura
spring.jpa.hibernate.ddl-auto=update

# Para poder ver la base de datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
